apiVersion: v1
kind: Namespace
metadata:
  name: game


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-so
  namespace: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-so
  template:
    metadata:
      labels:
        app: game-so
    spec:
      containers: 
      - name: game-so
        image: walymb/game-so:latest
---

apiVersion: v1
kind: Service
metadata:
  name: game-so-service
  namespace: game
spec:
  selector:
    app: game-so
  ports:
  - port: 8080
    targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-so-ingress
  namespace: game
  labels: 
    name: game-so-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  tls:
    - hosts:
      - game.waly.dev.br
      secretName: letsencrypt-prod
  rules:
  - host: game.waly.dev.br
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: game-so-service
            port:
              number: 8080

